spring.application.name=minierp
security.jwt.secret=MzIxNzY1NDMyMTc2NTQzMjE3NjU0MzIxNzY1NDMyMTc2NTQzMjE3NjU0MzIxNzY1NDMyMTc2NTQzMg==
security.jwt.expiration=3600
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
identity.bootstrap.admin.enabled=true
identity.bootstrap.admin.name=Administrador
identity.bootstrap.admin.email=admin@minierp.local
identity.bootstrap.admin.password=Admin@123
