spring.application.name=minierp
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:3600}

identity.bootstrap.admin.enabled=${IDENTITY_BOOTSTRAP_ADMIN_ENABLED:false}
identity.bootstrap.admin.name=${IDENTITY_BOOTSTRAP_ADMIN_NAME:Administrador}
identity.bootstrap.admin.email=${IDENTITY_BOOTSTRAP_ADMIN_EMAIL:}
identity.bootstrap.admin.password=${IDENTITY_BOOTSTRAP_ADMIN_PASSWORD:}
